version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  file-service:
    build: .
    environment:
      PORT: 8000
      MONGO_URI: mongodb://mongo:27017/file-service
      MONGO_QUOTA_COLLECTION_NAME: quotas
      MONGO_STATE_COLLECTION_NAME: states
      MONGO_FS_OBJECTS_COLLECTION_NAME: fsobjects
    ports:
      - 8000:8000
