version: '3.4'

services:
  mongo1:
    image: mongo
    restart: always
    command: [ '--bind_ip_all', '--replSet', 'rs0' ]
    ports:
      - 27017:27017

  mongo2:
    image: mongo
    restart: always
    command: [ '--bind_ip_all', '--replSet', 'rs0' ]

  mongo3:
    image: mongo
    restart: always
    command: [ '--bind_ip_all', '--replSet', 'rs0' ]

  mongosetup:
    image: mongo
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./scripts:/scripts
    restart: "no"
    entrypoint: [ "bash", "/scripts/setup_mongo.sh" ]

  file-service:
    build: .
    environment:
      LOAD_DOTENV: "false"
      PORT: 8000
      MONGO_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/file-service?replicaSet=rs0
      MONGO_QUOTAS_COLLECTION_NAME: quotas
      MONGO_STATES_COLLECTION_NAME: states
      MONGO_FS_OBJECTS_COLLECTION_NAME: fsobjects
    ports:
      - 8000:8000
