version: '3.4'

services:
  mongo:
    hostname: mongodb
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    command: [ "--replSet", "rs0", "--bind_ip_all" ]

  file-service:
    build: .
    environment:
      LOAD_DOTENV: "false"
      PORT: 8000
      MONGO_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/file-service?replicaSet=rs0
      MONGO_QUOTAS_COLLECTION_NAME: quotas
      MONGO_STATES_COLLECTION_NAME: states
      MONGO_FS_OBJECTS_COLLECTION_NAME: fsobjects
    network_mode: "host"
